name: Silly

on:
  # push:
    # branches: [ "main" ]
  workflow_dispatch:

jobs:
  iOS:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Get VLC
        run: git clone https://code.videolan.org/videolan/vlc-2.1.git --depth=1 --recursive -b 2.1.6
      - name: Install Dependencies
        run: brew reinstall autoconf automake nasm libtool bison m4 ragel help2man meson ninja yasm protobuf
      - name: Apply libVLC Patches
        run: cd vlc-2.1 && git apply ../vlckit-2.2.x-patches/*.patch
      - name: Compile libVLC
        run: |
          mkdir vlc-2.1/iOS
          cd vlc-2.1/iOS
          if [[ "${{ matrix.arch }}" == "arm64" ]] ; then
            bash ../extras/package/ios/build.sh -a arm64 -k $(xcodebuild -showsdks | grep 'iphoneos[0-9.]*' | awk '{print $NF}')
          else
            bash ../extras/package/ios/build.sh -a x86_64 -k $(xcodebuild -showsdks | grep 'iphonesimulator[0-9.]*' | awk '{print $NF}')
          fi
      - name: Strip libVLC
        run: |
          strip vlc-2.1/iOS/static-lib/libvlc-full-static.a
          mv vlc-2.1/iOS/static-lib/libvlc-full-static.a ~/libvlc-${{ matrix.arch }}.a
      - name: Upload libVLC
        uses: actions/upload-artifact@main
        with:
          name: iOS-${{ matrix.arch }}
          path: ~/libvlc*.a
          if-no-files-found: error
